jobs:
  fetch_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Fetch static secrets from Akeyless
        id: fetch-static-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          static-secrets: |
            - name: "/mysecret"
              output-name: "my_first_secret"
      - name: Use Akeyless secret
        run: |
            echo "Step Outputs"
            echo "my_first_secret: ${{ steps.fetch-secrets.outputs.my_first_secret }}"
            
    steps:
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secrets
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt        
          dynamic-secrets: |
            - name: "/mysqlDS"
              output-name: "mysql_dynamic_secret"
        
# ********* KEY TAKEAWAY  ********* #
# STEP 1 - Export Dynamic Secret's keys to env vars
    - name: Export Secrets to Environment
      run: |
        echo '${{ steps.fetch-dynamic-secrets.outputs.mysql_dynamic_secret }}' | jq -r 'to_entries|map("JWT_\(.key)=\(.value|tostring)")|.[]' >> $GITHUB_ENV

# STEP 2 - You can now access each secret separately as environment variables
    - name: Verify Vars
      run: |
        echo "MySQL DB Temporary Login: ${{ env.JWT_ID }}"
        echo "MySQL DB Temporary Password: ${{ env.JWT_PASSWORD }}"
