on: push

jobs:
  fetch_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch static secrets from Akeyless
        id: fetch-rotated-secret
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          static-secrets: |
            - name: "/mysql-account"
              output-name: "my_rotated_secret"
      - name: Output Akeyless Static Secret
        run: |
            echo "my_first_secret: ${{ steps.fetch-rotated-secret.outputs.my_rotated_secret }}"
      - name: Fetch dynamic secrets from Akeyless
        id: fetch-dynamic-secret
        uses: akeyless-community/akeyless-github-action@v1.0.1
        with:
          access-id: ${{ vars.AKEYLESS_ACCESS_ID }}
          access-type: jwt
          dynamic-secrets: |
            - name: "/mysqlDS"
              output-name: "mysql_dynamic_secret"
      - name: Export Secrets to Environment
        run: |
          echo '${{ steps.fetch-dynamic-secret.outputs.mysql_dynamic_secret }}' | jq -r 'to_entries|map("JWT_\(.key|ascii_upcase)=\(.value|tostring)")|.[]' >> $GITHUB_ENV
      - name: Verify Dynamic Credentials
        run: |
          echo "MySQL DB Temporary Login: ${{ env.JWT_ID }}"
          echo "MySQL DB Temporary Password: ${{ env.JWT_PASSWORD }}"
